### ISSUE TITLE
AutoPair and verify Pin methods Issue

### ISSUE THREAD

**Issue by kshitijvyas123** [status-im/status-keycard-java#17]
Hello,
Trying to use the code with my status keycard(It is black,).
I am able to fetch the info from it
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Instance UID: 8c82bedc0b65b9d75d5a9b6b29ee52d8
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Secure channel public key: 04187e3f406db8852fae444b635949e09140a556af6ef8ed0a7163ce0f01ad5d85be96f746a1cd2a2a21c90907eebd4cf99649b09969fc0514fefbd09a5143978c
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Application version: 2.1
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Free pairing slots: 0
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Key UID: 654cd70200be6f694a1ff76dce94b446cfb48543bae855419519ed9cb4459aa6
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Capabilities: 0F
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has Secure Channel: true
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has Key Management: true
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has Credentials Management: true
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has NDEF capability: true
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has cmdh: 0
08-20 15:21:41.543 9643-9663/im.status.keycard.demo D/CardChannel: COMMAND CLA: 80 INS: 20 P1: 00 P2: 00 LC: 06
08-20 15:21:41.629 9643-9663/im.status.keycard.demo D/CardChannel: RESPONSE LEN: 00, SW: 6985 
But when I am trying to call cmdSet.verifyPin("000000");

I am getting below error:

08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err: im.status.keycard.io.APDUException: SW_CONDITIONS_OF_USE_NOT_SATISFIED, 0x6985
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err:     at im.status.keycard.io.APDUResponse.checkSW(APDUResponse.java:91)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err:     at im.status.keycard.io.APDUResponse.checkOK(APDUResponse.java:64)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err:     at im.status.keycard.io.APDUResponse.checkAuthOK(APDUResponse.java:109)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err:     at im.status.keycard.app.MainActivity$1.onConnected(MainActivity.java:74)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err:     at im.status.keycard.android.NFCCardManager.onCardConnected(NFCCardManager.java:97)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err:     at im.status.keycard.android.NFCCardManager.run(NFCCardManager.java:80)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo E/MainActivity: SW_CONDITIONS_OF_USE_NOT_SATISFIED, 0x6985

Also when I am calling  cmdSet.autoPair("KeycardTest"); 
It gives me IO Exception.
Any thing which I am missing. Or I need to format the card and then intialize everything again

**Comment by bitgamma** [comment]
the cards are sent in a pre-initialized state, meaning they have no PIN, PUK or pairing key out of factory. You need to send an INIT command (you can use the SDK for this) to be able to actually use the card.

**Comment by kshitijvyas123** [comment]
Hello @bitgamma  Its already initalized . As There is a check in the code.

                    // First thing to do is selecting the applet on the card.
                    ApplicationInfo info = new ApplicationInfo(cmdSet.select().checkOK().getData());

                    Log.i(TAG, "Applet selection successful---"+info.isInitializedCard());

                    // If the card is not initialized, the INIT apdu must be sent. The actual PIN, PUK and             pairing password values
               
                    if (!info.isInitializedCard()) {
                        Log.e(TAG, "Initializing card with test secrets");
                        cmdSet.init("000000", "123456789012", "KeycardTest").checkOK();
                        info = new ApplicationInfo(cmdSet.select().checkOK().getData());
                    }
In the Log it is giving info.isInitializedCard()  TRUE. 
I guess thats why I am able to get all info from it.

**Comment by bitgamma** [comment]
are you running the demo as-is or did you do any change?

**Comment by kshitijvyas123** [comment]
I simply downloaded the demo and run it. Also I created a new demo app following API instructions . But same result.

**Comment by bitgamma** [comment]
please try downloading the latest applet from https://github.com/status-im/status-keycard/releases and installing it with https://github.com/status-im/keycard-cli (you can download binary releases from the release page) and see if you then have success running the demo (unmodified)

**Comment by kshitijvyas123** [comment]
https://github.com/status-im/keycard-cli/releases
I already have tried to download and install 0.0.11 and 0.0.12 , but not able to install them it just popup and vanish..
I will update you soon.
Just to confirm I am doing this for android application.

**Comment by kshitijvyas123** [comment]
@bitgamma  not able to run the .exe file.
What may be the possible cause of card not pairing issue. I need to give answer to higher authorities,

One more thing I want to know, In order to install the applet via CLI , do  need a card reader (If so which one?) or I can do it via NFC tap from mobile device(Some thing like that.)

**Comment by bitgamma** [comment]
@gravityblast can help you better with the keycard-cli tool. You need a USB card reader. Any PCSC compatible card reader will do (OmniKey 3121 for example)

**Comment by kshitijvyas123** [comment]
@bitgamma  one thing I need to ask. When It is showing available slots 0. Is this related to paring issue or not. because I think card has 6 available slots and if I have not done any thing yet then how come they filled.?

**Comment by gravityblast** [comment]
@kshitijvyas123 if you have a usb reader you can use https://github.com/status-im/keycard-cli to re-install it
