### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [status-im/status-keycard-java#20]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by bitgamma** [comment]
we use bouncycastle since some releases already. Did we forget removing references to spongycastle anywhere? Could you please give a pointer, I cannot find it

**Comment by Neustradamus** [comment]
@bitgamma: Thanks for your message!

- Here in this project "status-keycard-java": https://github.com/status-im/status-keycard-java/search?q=spongycastle&unscoped_q=spongycastle

- In "ethereumj-personal": https://github.com/status-im/ethereumj-personal/search?q=spongycastle&unscoped_q=spongycastle

- In "syng-client": https://github.com/status-im/syng-client/search?q=spongycastle&unscoped_q=spongycastle

It is for this I have created:
- https://github.com/status-im/status-keycard-java/issues/20
- https://github.com/status-im/ethereumj-personal/issues/10
- https://github.com/status-im/syng-client/issues/40

**Comment by Neustradamus** [comment]
@bitgamma: And in the same time an update of Bouncy Castle, currently last version is 1.65.

**Comment by Neustradamus** [comment]
@bitgamma: Thanks :)

**Comment by Neustradamus** [comment]
@bitgamma: Can you update Bouncy Castle to 1.69?
Note that there were CVEs before.
