### ISSUE TITLE
factory reset

### ISSUE THREAD

**Issue by hiletmis** [status-im/status-keycard-java#23]
Official status app has the ability to factory reset the keycard but the keycard api does not have such option.
There is only remove key option which requires secure channel. 

How can I factory reset keycard using the api?

Thanks!

**Comment by bitgamma** [comment]
Hi,

you need to use the GlobalPlatformCommandSet. You can see the implementation we use at

https://github.com/status-im/react-native-status-keycard/blob/af61b0213adbf4b5a6bae97c85496d95007d5acb/android/src/main/java/im/status/ethereum/keycard/SmartCard.java#L278

**Comment by hiletmis** [comment]
thanks! now I have managed to reset the keycard.
