### ISSUE TITLE
Signing a transaction

### ISSUE THREAD

**Issue by MhAhmadAli** [status-im/status-keycard-java#31]
I am working on keycard and wanted to know how can I sign a transaction?

I have tried the sign method but its not working for me. Do I need to export the private key from the keycard and sign the transaction that way? or is there a method to sign it without exporting the private key from keycard?

**Comment by bitgamma** [comment]
You cannot export the private key from Keycard (except in a specific subpath) and you should let the card sign. You first need to hash your tx though, the card only signs the hash.

You can find details at https://keycard.tech/docs/sdk/derivation_sign.html in particular read the paragraph `Combined derivation and sign`

**Comment by MhAhmadAli** [comment]
The docs you linked only mention about signing a message and It follows the `personal_sign` standard. It only accepts a hash with a length of 32.

It doesn't seem to work for me as It's not returning a valid signed transaction that can be sent to the chain.

If you have a working example of transaction signing then that would be helpful. I have looked through the demo app in the repo but that doesn't contain anything regarding transaction signing.

**Comment by bitgamma** [comment]
Actually what I linked is the generic (and only) way to sign with Keycard. You need to hash the transaction yourself then sign the hash with Keycard. We don't have simple examples about doing that.

**Comment by MhAhmadAli** [comment]
There is a limit for data length to be 32 bytes in that method.

None of the transactions are 32 bytes long as far as I know.
